n = input('Digite algo: ')
print('O tipo primitivo deste valor é: ', type(n))
print('Só tem espaços em branco? ', n.isspace())
print('É um número? ', n.isnumeric())
print('É alfabético? ', n.isalpha())
print('É alfanumérico? ', n.isalnum())
print('Está escrito em maiúsculo? ', n.isupper())
print('Está escrito em minúsculo? ', n.islower())
print('Está capitalizada? ', n.istitle())
